name: build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - run: mvn clean test --batch-mode -Dmaven.test.failure.ignore=true
      - name: Update existing check report
        uses: starburstdata/action-testng-report@master
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: build
          update_existing_check: true
          report_paths: "*"
      - name: Create new check report
        uses: starburstdata/action-testng-report@master
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: new check name
          report_paths: "*"